#!/usr/bin/env bash
# Regenerate results/benchmark.md from scratch by running `nd` on every example
# weight/test pair. Nothing in the table is hand-written: each cell is parsed
# from the output of `nd stats`, `nd slice` and `nd verify`.
#
#   scripts/bench.sh            # build nd (release) and write results/benchmark.md
#   EPS=0.15 scripts/bench.sh   # quantization epsilon (nd default is 0.15)
#
# Pairs are discovered dynamically: every `examples/**/<t>.json` with a sibling
# `examples/**/<t>_tests.json` is benchmarked, except `examples/bci/**` (that
# pipeline has its own report at results/bci.md, generated by `make bci`) and
# `examples/train_logs/**` (training logs, not weight files). The one legacy
# exception is `examples/mod5_weights.json` + `examples/mod5_tests.json`,
# whose basenames don't match; it is paired explicitly below.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

EPS="${EPS:-0.15}"
OUT="${OUT:-results/benchmark.md}"
ND="${ND:-target/release/nd}"

if [[ "$ND" == "target/release/nd" ]]; then
  if ! build_log="$(cargo build --release --quiet 2>&1)"; then
    echo "$build_log" >&2; echo "cargo build failed" >&2; exit 1
  fi
fi
[[ -x "$ND" ]] || { echo "nd binary not found at $ND" >&2; exit 1; }

mkdir -p "$(dirname "$OUT")"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# --- collect (name, weights, tests) triples ---------------------------------
declare -a NAMES WEIGHTS TESTS
add_pair() { NAMES+=("$1"); WEIGHTS+=("$2"); TESTS+=("$3"); }

while IFS= read -r w; do
  [[ -f "$w" ]] || continue
  t="${w%.json}_tests.json"
  [[ -f "$t" ]] || continue
  add_pair "$(basename "${w%.json}")" "$w" "$t"
done < <(find examples -name '*.json' ! -name '*_tests.json' \
            -not -path 'examples/bci/*' -not -path 'examples/train_logs/*' | sort)
if [[ -f examples/mod5_weights.json && -f examples/mod5_tests.json ]]; then
  add_pair mod5 examples/mod5_weights.json examples/mod5_tests.json
fi


# --- run nd on each pair -----------------------------------------------------
ROWS="$(mktemp)"
trap 'rm -f "$TMP" "$ROWS"' EXIT
n_total=0; n_rnn=0; n_perfect=0; n_allint=0

for i in "${!NAMES[@]}"; do
  name="${NAMES[$i]}"; w="${WEIGHTS[$i]}"; t="${TESTS[$i]}"

  stats="$("$ND" stats "$w" --eps "$EPS" 2>&1)"
  verify="$("$ND" verify "$w" "$t" --eps "$EPS" 2>&1)"

  kind=RNN
  grep -q "Statistics (Transformer)" <<<"$stats" && kind=Transformer

  if [[ $kind == RNN ]]; then
    n_rnn=$((n_rnn + 1))
    slice="$("$ND" slice "$w" "$t" --eps "$EPS" 2>&1)"
    hidden="$(sed -n 's/^Hidden dim: *//p' <<<"$stats" | head -1)"
    live="$(sed -n 's/^Active circuit: \([0-9]*\) neurons.*/\1/p' <<<"$slice" | head -1)"
    integer="$(sed -n 's/^Integer (eps=[^)]*): *\([0-9]*\)\/\([0-9]*\) (\([0-9]*\)%).*/\1\/\2 (\3%)/p' <<<"$stats" | head -1)"
    all_int="$(sed -n 's/^Integer (eps=[^)]*): *\([0-9]*\)\/\([0-9]*\) .*/\1 \2/p' <<<"$stats" | awk 'NR==1 && $1==$2 {print "yes"}')"
  else
    hidden="d_model=$(sed -n 's/.*d_model=\([0-9]*\).*/\1/p' <<<"$stats" | head -1)"
    live=""; integer=""; all_int=""
  fi
  vline="$(grep -E 'Verification: [0-9]+/[0-9]+ passed' <<<"$verify" | head -1)"
  vp="$(sed -n 's/.*Verification: \([0-9]*\)\/\([0-9]*\) passed.*/\1/p' <<<"$vline")"
  vt="$(sed -n 's/.*Verification: \([0-9]*\)\/\([0-9]*\) passed.*/\2/p' <<<"$vline")"

  [[ -n "$hidden" && "$vp" =~ ^[0-9]+$ && "$vt" =~ ^[1-9][0-9]*$ ]] || {
    printf 'Failed to parse benchmark for %s\n%s\n%s\n' "$name" "$stats" "$verify" >&2
    exit 1
  }
  [[ -z "$live"    ]] && live="n/a"
  [[ -z "$integer" ]] && integer="n/a"
  if [[ -n "$vp" ]]; then
    verify_cell="$vp/$vt"
    pctv=$(( 100 * vp / vt ))
    verify_cell="$verify_cell ($pctv%)"
    (( vp == vt )) && n_perfect=$((n_perfect + 1))
  else
    verify_cell="ERR"
  fi
  n_total=$((n_total + 1))
  [[ "$all_int" == "yes" ]] && n_allint=$((n_allint + 1))

  printf '| %s | %s | %s | %s | %s | %s |\n' \
    "$name" "$kind" "$hidden" "$live" "$verify_cell" "$integer" >> "$ROWS"
done

[[ "$n_total" -gt 0 ]] || { echo "No benchmark pairs found" >&2; exit 1; }

# --- write the markdown ------------------------------------------------------
{
  echo "# Benchmark"
  echo
  echo "Generated by \`scripts/bench.sh\` (do not edit by hand) on $(date -u +%Y-%m-%d) with"
  echo "base commit \`$(git rev-parse --short HEAD 2>/dev/null || echo unknown)\` (working-tree source), quantization eps = $EPS."
  echo "Binary SHA-256: \`$(sha256sum "$ND" | cut -d ' ' -f 1)\`."
  echo
  echo "| Task | Kind | Hidden dim | Live neurons | Verify | Integer weights |"
  echo "|------|------|-----------:|-------------:|-------:|----------------:|"
  sort "$ROWS"
  echo
  echo "- **Hidden dim**: \`nd stats\` (\`d_model\` for transformers)."
  echo "- **Live neurons**: \`nd slice <weights> <tests>\` — neurons that fire on some test input and can reach the output."
  echo "- **Verify**: \`nd verify <weights> <tests>\` — quantized FSM (or transformer) vs. the test set (exhaustive for the finite tasks)."
  echo "- **Integer weights**: \`nd stats\` — weights within 0.01 of an integer after epsilon snapping (not an exact-equality metric)."
  echo
  echo "**$n_perfect/$n_total** pairs verify 100%; **$n_allint/$n_rnn** RNNs have every weight within 0.01 of an integer."
  echo
  echo "Reproduce: \`make bench\`. Retrain the RNN tasks with \`make train\` (\`scripts/train_rnn_tasks.py\`)."
} > "$TMP"

chmod 644 "$TMP"
mv "$TMP" "$OUT"
trap 'rm -f "$ROWS"' EXIT
echo "Wrote $OUT"
cat "$OUT"
