#!/usr/bin/env bash
# check_circuits.sh — keep the circuits that Kani proves about *literally* equal to what `nd` emits.
#
#   ./check_circuits.sh            # regenerate in a temp file and diff against src/generated.rs (exit 1 on drift)
#   ./check_circuits.sh --update   # rewrite src/generated.rs from the current `nd` output
#
# For every example weight file below we run
#     nd decompile <weights.json> --format rust-kani
# and splice the *verbatim* `fn decompiled(...)` it prints into src/generated.rs, together with two
# mechanically derived functions (a pure text split of the same lines, no re-typing of coefficients;
# the only edit to nd's text is prefixing `pub` to `fn decompiled`):
#     step(h, x0, x1, ..)  = the loop body of `decompiled`   (one RNN step)
#     output(h)            = the epilogue of `decompiled`    (logits + argmax)
# The inductive proofs in src/*.rs are written against `step` / `output`; src/equiv.rs proves with
# Kani that folding `step` + `output` is the same function as the verbatim `decompiled`.
#
# As a last sanity check the script also runs `nd verify` on each example's test file.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$HERE")"
ND="${ND:-$ROOT/target/release/nd}"
OUT="$HERE/src/generated.rs"

if [[ ! -x "$ND" ]]; then
  echo "building nd (release)..." >&2
  (cd "$ROOT" && cargo build --release >&2)
fi

# name:weights:tests
CIRCUITS=(
  "contains_11:examples/regex/contains_11.json:examples/regex/contains_11_tests.json"
  "no_consecutive_1:examples/regex/no_consecutive_1.json:examples/regex/no_consecutive_1_tests.json"
  "divisible_by_3:examples/regex/divisible_by_3.json:examples/regex/divisible_by_3_tests.json"
  "parity3:examples/parity3.json:examples/parity3_tests.json"
  "mod3_add:examples/mod3_add.json:examples/mod3_add_tests.json"
)

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "// @generated by kani-proofs/check_circuits.sh --update — DO NOT EDIT BY HAND."
  echo "//"
  echo "// Each module contains, verbatim, the \`fn decompiled\` printed by"
  echo "//     nd decompile <weights.json> --format rust-kani"
  echo "// plus \`step\`/\`output\`, a mechanical split of that function's loop body / epilogue."
  echo "// Run ./check_circuits.sh to confirm this file still matches the current \`nd\` output."
  echo "#![allow(clippy::all, unused, dead_code)]"
} > "$TMP"

for entry in "${CIRCUITS[@]}"; do
  IFS=: read -r name weights tests <<<"$entry"
  (cd "$ROOT" && "$ND" decompile "$weights" --format rust-kani 2>/dev/null) \
    | python3 -c '
import re, sys
name, weights = sys.argv[1], sys.argv[2]
lines = sys.stdin.read().split("\n")
s = next(i for i, l in enumerate(lines) if l.startswith("fn decompiled("))
e = next(i for i in range(s, len(lines)) if lines[i] == "}")
d = s
while d > 0 and lines[d - 1].startswith("///"):
    d -= 1
verbatim = lines[d:e + 1]
m = re.search(r"seq: &\[\[(\w+); (\d+)\]\]", lines[s]);  assert m, "input signature"
xt, xd = m.group(1), int(m.group(2))
m = re.search(r"let mut h: \[(\w+); (\d+)\]", "\n".join(lines[s:e]));  assert m, "state decl"
ht, hn = m.group(1), int(m.group(2))
w = next(i for i in range(s, e) if lines[i].strip() == "while i < len {")
inc = next(i for i in range(w, e) if lines[i].strip() == "i += 1;")
body = lines[w + 1:inc]
close = inc + 1
assert lines[close] == "    }", "loop close"
epilogue = lines[close + 1:e]
xs = [l for l in body if re.match(r"\s*let x\d+ = seq\[i\]\[\d+\];", l)]
hs = [l for l in body if re.match(r"\s*let h\d+ = ", l)]
ret = [l for l in body if re.match(r"\s*h = \[", l)]
assert len(xs) == xd and len(hs) == hn and len(ret) == 1, (len(xs), len(hs), len(ret))
assert len(xs) + len(hs) + len(ret) == len(body), "unrecognised statement in loop body"
params = ", ".join(f"x{k}: {xt}" for k in range(xd))
print(f"pub mod {name} {{")
print(f"    // Source weights: {weights}")
print("    // ---- verbatim `nd decompile --format rust-kani` output ----")
for l in verbatim:
    # only change to nd'"'"'s text: make the function reachable from the proof modules
    if l.startswith("fn decompiled("):
        l = "pub " + l
    print(("    " + l).rstrip())
print("    // ---- mechanical split of the function above ----")
print(f"    pub const HIDDEN: usize = {hn};")
print(f"    pub fn step(h: [{ht}; {hn}], {params}) -> [{ht}; {hn}] {{")
for l in hs:
    print(l.rstrip())
print("        " + ret[0].strip().replace("h = ", "", 1).rstrip(";"))
print("    }")
print(f"    pub fn output(h: [{ht}; {hn}]) -> usize {{")
for l in epilogue:
    print(("    " + l).rstrip())
print("    }")
print("}")
' "$name" "$weights" >> "$TMP"
done

if [[ "${1:-}" == "--update" ]]; then
  cp "$TMP" "$OUT"
  echo "updated $OUT"
else
  if diff -u "$OUT" "$TMP"; then
    echo "OK: src/generated.rs matches current nd output for ${#CIRCUITS[@]} circuits"
  else
    echo "DRIFT: src/generated.rs differs from current nd output (run ./check_circuits.sh --update)" >&2
    exit 1
  fi
fi

# Sanity: nd itself agrees with the example test files.
for entry in "${CIRCUITS[@]}"; do
  IFS=: read -r name weights tests <<<"$entry"
  res="$(cd "$ROOT" && "$ND" verify "$weights" "$tests" 2>/dev/null | grep -m1 '^Verification:' || true)"
  echo "nd verify $name: $res"
  [[ "$res" == *"(100%)"* ]] || { echo "nd verify did not reach 100% for $name" >&2; exit 1; }
done
