// @generated by kani-proofs/check_circuits.sh --update — DO NOT EDIT BY HAND.
//
// Each module contains, verbatim, the `fn decompiled` printed by
//     nd decompile <weights.json> --format rust-kani
// plus `step`/`output`, a mechanical split of that function's loop body / epilogue.
// Run ./check_circuits.sh to confirm this file still matches the current `nd` output.
#![allow(clippy::all, unused, dead_code)]
pub mod contains_11 {
    // Source weights: examples/regex/contains_11.json
    // ---- verbatim `nd decompile --format rust-kani` output ----
    /// Auto-decompiled by neural-decompile (Kani-friendly)
    /// Integer arithmetic, 1 live neurons (of 2)
    pub fn decompiled(seq: &[[i64; 2]], len: usize) -> usize {
        let mut h: [i64; 1] = [0; 1];
        let mut i = 0;
        while i < len {
            let x0 = seq[i][0];
            let x1 = seq[i][1];
            let h0 = (2 * h[0] + -1 * x0 + 2 * x1 + -1).max(0);
            h = [h0];
            i += 1;
        }
        let l0 = -2 * h[0] + 3;
        let l1 = 2 * h[0] + -3;
        if l1 > l0 { 1 } else { 0 }
    }
    // ---- mechanical split of the function above ----
    pub const HIDDEN: usize = 1;
    pub fn step(h: [i64; 1], x0: i64, x1: i64) -> [i64; 1] {
        let h0 = (2 * h[0] + -1 * x0 + 2 * x1 + -1).max(0);
        [h0]
    }
    pub fn output(h: [i64; 1]) -> usize {
        let l0 = -2 * h[0] + 3;
        let l1 = 2 * h[0] + -3;
        if l1 > l0 { 1 } else { 0 }
    }
}
pub mod no_consecutive_1 {
    // Source weights: examples/regex/no_consecutive_1.json
    // ---- verbatim `nd decompile --format rust-kani` output ----
    /// Auto-decompiled by neural-decompile (Kani-friendly)
    /// Integer arithmetic, 1 live neurons (of 2)
    pub fn decompiled(seq: &[[i64; 2]], len: usize) -> usize {
        let mut h: [i64; 1] = [0; 1];
        let mut i = 0;
        while i < len {
            let x0 = seq[i][0];
            let x1 = seq[i][1];
            let h0 = (2 * h[0] + -1 * x0 + 2 * x1 + -1).max(0);
            h = [h0];
            i += 1;
        }
        let l0 = 2 * h[0] + -3;
        let l1 = -2 * h[0] + 3;
        if l1 > l0 { 1 } else { 0 }
    }
    // ---- mechanical split of the function above ----
    pub const HIDDEN: usize = 1;
    pub fn step(h: [i64; 1], x0: i64, x1: i64) -> [i64; 1] {
        let h0 = (2 * h[0] + -1 * x0 + 2 * x1 + -1).max(0);
        [h0]
    }
    pub fn output(h: [i64; 1]) -> usize {
        let l0 = 2 * h[0] + -3;
        let l1 = -2 * h[0] + 3;
        if l1 > l0 { 1 } else { 0 }
    }
}
pub mod divisible_by_3 {
    // Source weights: examples/regex/divisible_by_3.json
    // ---- verbatim `nd decompile --format rust-kani` output ----
    /// Auto-decompiled by neural-decompile (Kani-friendly)
    /// Integer arithmetic, 4 live neurons (of 5)
    pub fn decompiled(seq: &[[i64; 2]], len: usize) -> usize {
        let mut h: [i64; 4] = [0; 4];
        let mut i = 0;
        while i < len {
            let x0 = seq[i][0];
            let x1 = seq[i][1];
            let h0 = (-1 * h[0] + 1 * h[1] + -3 * h[2] + 2 * x1).max(0);
            let h1 = (1 * h[0] + 1 * h[2] + -2 * x1).max(0);
            let h2 = (1 * h[0] + 1 * h[2] + 1 * h[3] + -4 * x1 + -2).max(0);
            let h3 = (1 * h[0] + -1 * h[1] + 1 * h[2] + -2 * x1).max(0);
            h = [h0, h1, h2, h3];
            i += 1;
        }
        let l0 = 5 * h[0] + 3 * h[1] + 3 * h[2] + 3 * h[3] + -4;
        let l1 = -5 * h[0] + -3 * h[1] + -3 * h[2] + -3 * h[3] + 4;
        if l1 > l0 { 1 } else { 0 }
    }
    // ---- mechanical split of the function above ----
    pub const HIDDEN: usize = 4;
    pub fn step(h: [i64; 4], x0: i64, x1: i64) -> [i64; 4] {
        let h0 = (-1 * h[0] + 1 * h[1] + -3 * h[2] + 2 * x1).max(0);
        let h1 = (1 * h[0] + 1 * h[2] + -2 * x1).max(0);
        let h2 = (1 * h[0] + 1 * h[2] + 1 * h[3] + -4 * x1 + -2).max(0);
        let h3 = (1 * h[0] + -1 * h[1] + 1 * h[2] + -2 * x1).max(0);
        [h0, h1, h2, h3]
    }
    pub fn output(h: [i64; 4]) -> usize {
        let l0 = 5 * h[0] + 3 * h[1] + 3 * h[2] + 3 * h[3] + -4;
        let l1 = -5 * h[0] + -3 * h[1] + -3 * h[2] + -3 * h[3] + 4;
        if l1 > l0 { 1 } else { 0 }
    }
}
pub mod parity3 {
    // Source weights: examples/parity3.json
    // ---- verbatim `nd decompile --format rust-kani` output ----
    /// Auto-decompiled by neural-decompile (Kani-friendly)
    /// Integer arithmetic, 3 live neurons (of 3)
    pub fn decompiled(seq: &[[i64; 2]], len: usize) -> usize {
        let mut h: [i64; 3] = [0; 3];
        let mut i = 0;
        while i < len {
            let x0 = seq[i][0];
            let x1 = seq[i][1];
            let h0 = (1 * h[1] + 1 * h[2] + 3 * x0 + -1 * x1).max(0);
            let h1 = (-1 * h[1] + 1 * h[2] + 2 * x0 + -1 * x1 + 1).max(0);
            let h2 = (1 * h[0] + 1 * h[1] + -1 * h[2] + 1 * x0 + -1 * x1).max(0);
            h = [h0, h1, h2];
            i += 1;
        }
        let l0 = -2 * h[0] + 2 * h[1] + 2 * h[2] + -1;
        let l1 = 2 * h[0] + -2 * h[1] + -2 * h[2] + 1;
        if l1 > l0 { 1 } else { 0 }
    }
    // ---- mechanical split of the function above ----
    pub const HIDDEN: usize = 3;
    pub fn step(h: [i64; 3], x0: i64, x1: i64) -> [i64; 3] {
        let h0 = (1 * h[1] + 1 * h[2] + 3 * x0 + -1 * x1).max(0);
        let h1 = (-1 * h[1] + 1 * h[2] + 2 * x0 + -1 * x1 + 1).max(0);
        let h2 = (1 * h[0] + 1 * h[1] + -1 * h[2] + 1 * x0 + -1 * x1).max(0);
        [h0, h1, h2]
    }
    pub fn output(h: [i64; 3]) -> usize {
        let l0 = -2 * h[0] + 2 * h[1] + 2 * h[2] + -1;
        let l1 = 2 * h[0] + -2 * h[1] + -2 * h[2] + 1;
        if l1 > l0 { 1 } else { 0 }
    }
}
pub mod mod3_add {
    // Source weights: examples/mod3_add.json
    // ---- verbatim `nd decompile --format rust-kani` output ----
    /// Auto-decompiled by neural-decompile (Kani-friendly)
    /// Float arithmetic, 3 live neurons (of 3)
    pub fn decompiled(seq: &[[f64; 3]], len: usize) -> usize {
        let mut h: [f64; 3] = [0.0; 3];
        let mut i = 0;
        while i < len {
            let x0 = seq[i][0];
            let x1 = seq[i][1];
            let x2 = seq[i][2];
            let h0 = (-1.0 * h[1] + 1.0 * h[2] + 2.0 * x0 + -2.0 * x1).max(0.0);
            let h1 = (0.5614603757858276 * h[0] + -1.0 * h[2] + -1.0 * x0 + 2.0 * x2).max(0.0);
            let h2 = (1.0 * h[1] + -1.0 * h[2] + -2.0 * x0 + 2.0 * x1).max(0.0);
            h = [h0, h1, h2];
            i += 1;
        }
        let logits: [f64; 3] = [
            1.0 * h[0] + -2.0 * h[1] + 1.0 * h[2],
            2.0 * h[0] + 2.0 * h[1] + 1.0 * h[2] + -3.0,
            -2.0 * h[0] + 1.0 * h[1] + -2.0 * h[2] + 2.0,
        ];
        let mut best = 0;
        let mut k = 1;
        while k < 3 {
            if logits[k] > logits[best] { best = k; }
            k += 1;
        }
        best
    }
    // ---- mechanical split of the function above ----
    pub const HIDDEN: usize = 3;
    pub fn step(h: [f64; 3], x0: f64, x1: f64, x2: f64) -> [f64; 3] {
        let h0 = (-1.0 * h[1] + 1.0 * h[2] + 2.0 * x0 + -2.0 * x1).max(0.0);
        let h1 = (0.5614603757858276 * h[0] + -1.0 * h[2] + -1.0 * x0 + 2.0 * x2).max(0.0);
        let h2 = (1.0 * h[1] + -1.0 * h[2] + -2.0 * x0 + 2.0 * x1).max(0.0);
        [h0, h1, h2]
    }
    pub fn output(h: [f64; 3]) -> usize {
        let logits: [f64; 3] = [
            1.0 * h[0] + -2.0 * h[1] + 1.0 * h[2],
            2.0 * h[0] + 2.0 * h[1] + 1.0 * h[2] + -3.0,
            -2.0 * h[0] + 1.0 * h[1] + -2.0 * h[2] + 2.0,
        ];
        let mut best = 0;
        let mut k = 1;
        while k < 3 {
            if logits[k] > logits[best] { best = k; }
            k += 1;
        }
        best
    }
}
